# Project: CloudKart
# File: 06-mongodb-service.yaml
# Description: Kubernetes manifest file.
# How to use: Applied to the cluster via 'kubectl apply' or ArgoCD.
# Why it exists: To define desired state of K8s resources.
# When it's used: During application deployment to EKS.

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: cloudkart
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb