apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudkart-config
  namespace: cloudkart
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/cloudkart"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://cloudkart.buildwithkanha.shop/api"
  NEXTAUTH_URL: "https://cloudkart.buildwithkanha.shop/"
  NEXTAUTH_SECRET: "d9Ddo4p4or58ERfSPij4Skp7hXt8puYERlTETxlhJ7A="
  JWT_SECRET: "66cdad2a74101704d3430e43ee3511009e6bf40b260211cd4f8c6d6b2e73ed3f"
