# Project: CloudKart
# File: 04-configmap.yaml
# Description: Kubernetes manifest file.
# How to use: Applied to the cluster via 'kubectl apply' or ArgoCD.
# Why it exists: To define desired state of K8s resources.
# When it's used: During application deployment to EKS.

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudkart-config
  namespace: cloudkart
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/cloudkart"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://app.52.48.50.175.nip.io/api"
  NEXTAUTH_URL: "http://app.52.48.50.175.nip.io/"
