# Project: CloudKart
# File: 11-hpa.yaml
# Description: Kubernetes manifest file.
# How to use: Applied to the cluster via 'kubectl apply' or ArgoCD.
# Why it exists: To define desired state of K8s resources.
# When it's used: During application deployment to EKS.

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloudkart-hpa
  namespace: cloudkart
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudkart
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70