apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: cloudkart
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: migration
        image: kanhaiyatiwari/cloudkart-migration:19
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/cloudkart"
      restartPolicy: OnFailure
