apiVersion: v1
kind: Secret
metadata:
  name: cloudkart-secrets
  namespace: cloudkart
type: Opaque
stringData:
  JWT_SECRET: "change-this-in-production"
  NEXTAUTH_SECRET: "change-this-in-production"