# Project: CloudKart
# File: 05-sc.yaml
# Description: Kubernetes manifest file.
# How to use: Applied to the cluster via 'kubectl apply' or ArgoCD.
# Why it exists: To define desired state of K8s resources.
# When it's used: During application deployment to EKS.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
